version: '3.8'

services:
  # 主服务
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/config/config.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro  # 用于Docker管理
    environment:
      - MCP_LOG_LEVEL=info
      - MCP_LOG_FORMAT=json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/mcp-server", "-version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 测试服务 - 用于集成测试
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - GO_ENV=test
    profiles:
      - test
    command: ["./test.sh", "-a", "-v"]

  # 开发环境
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
      - "2345:2345"  # Delve调试端口
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - GO_ENV=development
      - MCP_LOG_LEVEL=debug
    profiles:
      - dev
    command: ["air", "-c", ".air.toml"]  # 热重载

  # 文档服务
  docs:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./docs:/usr/share/nginx/html:ro
      - ./README_CN.md:/usr/share/nginx/html/index.md:ro
    profiles:
      - docs

volumes:
  go_modules:
    driver: local

networks:
  default:
    name: mcp-server-network