version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: unla_mysql
    environment:
      MYSQL_ROOT_PASSWORD: nov24feb11
      MYSQL_DATABASE: unla_gateway
    ports:
      - "3311:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: unla_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data: