# Simple Unla MCP Gateway Configuration
storage:
  type: disk  # Use file-based storage for simplicity
  
disk:
  path: "./test_mcp_gateway/configs"  # Store config files here

# Server configuration
server:
  host: 0.0.0.0
  port: 8081

# Notifier configuration (optional)
notifier:
  role: receiver
  type: signal