# Unla MCP Gateway Configuration with SQLite
storage:
  type: db

# Database configuration using SQLite
database:
  type: sqlite
  dbname: "./test_mcp_gateway/unla-gateway.db"

# Server configuration
server:
  host: 0.0.0.0
  port: 8081

# Notifier configuration
notifier:
  role: receiver
  type: signal